### ISSUE TITLE
Deleting a user

### ISSUE THREAD

**Issue by BenMorganIO** [sailthru/sailthru-ruby-client#61]
To delete a user, I've tried:

```ruby
sailthru.api_delete(:user, key: user.email)
# => {"error"=>1, "errormsg"=>"Unsupported HTTP method: DELETE"}
```

How do I go about deleting a user? I've figured out how to create, read, and update, but not delete.

**Comment by duanmua** [comment]
+1

**Comment by Dude-X** [comment]
We don't delete users in order to preserve the ability to reconcile and report on our data. Due to the user focus of our platform, nearly all of our data is tied to a user, and because we must retain historical event data (purchases, pageviews, etc) we need to retain the user record those events are tied to. In addition, we have legal requirements (like CAN-SPAM) to respect a user's choice to opt-out of communications, and respect privacy settings. If we delete such users, we are at risk of illegally sending emails.

If there is a serious issue regarding your profiles, you may contact your account manager or customer support for assistance.

**Comment by BenMorganIO** [comment]
@Dude-X Maybe we could add a flag such as `deleted_at` to flag when a user has been deleted in a clients application?

**Comment by Dude-X** [comment]
I don't know of any plans to support soft delete. However, users can be removed from lists, so that they don't get included in a campaign.

**Comment by BenMorganIO** [comment]
@Dude-X is there a way to remove a user from a list using the current version of the gem?

**Comment by Dude-X** [comment]
Using the client:
`save_user("me@example.com", {"lists": {"My List" : 0})`
otherwise `POST {"id": "me@example.com", "lists": {"My List": 0}}`
The "lists" field accepts a dictionary/hash that can represent lists to add or remove from.
Example: `"lists": {"My List": 1, "My Other List": 0, "New List": 1}` would add a user to "My List" and "New List" but remove that user from "My Other List".
